require "fileutils"
require "rake/clean"

file "data" do
  mkdir "data"
  mkdir "data/parse_problem"
  mkdir "data/download_problem_statement"
  mkdir "data/download_problem_detail"
  mkdir "data/download_problem_solution"
  mkdir "data/generate_problem_dir"
end

def inspector(name, output)
  unless File.exists?(output) then
    ruby "-Ilib inspect/gettc/#{name}_inspect.rb"
  end
end

def tester name
  ruby "-Ilib test/gettc/#{name}_test.rb"
end

namespace :inspect do
  desc "Inspect the downloader"
  task download: "data" do
    inspector "download", "data/download_problem_statement/Checker.htm"
  end

  desc "Inspect the parser"
  task parse: "inspect:download" do
    inspector "parse", "data/parse_problem/Checker.yml"
  end

  desc "Inspect the generator"
  task generate: "inspect:parse" do
    inspector "generate", "data/generate_problem_dir/BuildingRoads"
  end

end

namespace :test do
  desc "Test the types"
  task :types do
    tester "types"
  end

  desc "Test the signature"
  task :signature do
    tester "signature"
  end

  desc "Test the downloader"
  task :download do
    tester "download"
  end

  desc "Test the parser"
  task :parse => "inspect:download" do
    tester "parse"
  end

  desc "Test the generator"
  task :generate do
    tester "generate"
  end

  desc "Test everything"
  task all: %w[test:types test:signature test:download test:parse test:generate] do
  end
end
