require "fileutils"
require "rake/clean"

STATEMENT_FILE = "data/statements/CirlesCountry.html"

file "data" do
  mkdir "data"
  mkdir "data/statements"
  mkdir "data/details"
  mkdir "data/solutions"
  mkdir "data/parsed"
  mkdir "data/generated"
end

file STATEMENT_FILE => "test:download" do
end

def execute_test(name)
  ruby "-Ilib -I. test/gettc/#{name}_test.rb"
end

namespace :test do
  desc "Test the types"
  task :types do
    execute_test("types")
  end

  desc "Test the signature"
  task :signature do
    execute_test("signature")
  end

  desc "Test the downloader"
  task download: "data" do
    execute_test("download")
  end

  desc "Test the parser"
  task parse: STATEMENT_FILE do
    execute_test("parse")
  end

  desc "Test the generator"
  task :generate do
    execute_test("generate")
  end

  desc "Test everything"
  task all: %w[test:types test:signature test:download test:parse test:generate] do
  end
end
